In [1]:
import numpy as np


In [7]:
#Step1: Collect data
X= np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
Y = np.array([[0],[1],[1],[0]])

In [5]:
print(X)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [6]:
print(Y)


[[0]
 [1]
 [1]
 [0]]


In [12]:
# Step2: Build Model
num_epochs = 60000
#initialize weights
# This is for input node : size is 3*4 and weight value is -1<w<1
syn0 = 2*np.random.random((3,4)) - 1
#This is from hidden node to output node : size needs to be 4*1 and weeight needs to be -1<w<1
syn1 = 2*np.random.random((4,1)) - 1


In [9]:
print(syn0)

[[-0.29218349  0.5386815   0.97002551 -0.23058706]
 [-0.01260555  0.70336317 -0.18006498  0.63761372]
 [ 0.30755758  0.31912164 -0.69950535  0.18957302]]


In [15]:
print(syn1)

[[ 0.16777306]
 [-0.34574681]
 [ 0.410445  ]
 [ 0.39800252]]


In [21]:
#Sigmoid function for activation function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)

    return 1/(1+np.exp(-x))

#Step 3 Train Model
for j in range(num_epochs):
    #feed forward through layers 0,1, and 2
    k0 = X
    k1 = nonlin(np.dot(k0, syn0))
    k2 = nonlin(np.dot(k1, syn1))
    #how much did we miss the target value?
    k2_error = Y - k2
    
    if (j% 10000) == 0:
        print( "Error:" + str(np.mean(np.abs(k2_error))))
    
    #in what direction is the target value?
    k2_delta = k2_error*nonlin(k2, deriv=True)
    
    #how much did each k1 value contribute to k2 error
    #backpropogation- update weight value
    k1_error = k2_delta.dot(syn1.T)
    
    #in what direction is the target value?
    k1_delta= k1_error * nonlin(k1,deriv=True)
    
    
    syn1 += k1.T.dot(k2_delta)
    syn0 += k0.T.dot(k1_delta)
    





Error:0.49999426512
Error:0.00947698935365
Error:0.00647411114489
Error:0.00521180008737
Error:0.00447669096137
Error:0.00398200751246
